### ISSUE TITLE
Patch to support old version of matlab

### ISSUE THREAD

**Issue by neurolabusc** [wichmann-lab/psignifit#3]
Current software fails on older versions of Matlab. This can be fixed by changing line 86 of plotPsych from `if verLessThan('matlab', 'R2013a')` to read `if verLessThan('matlab', '8.1')`, to match the expectation of verLessThan : `VERSION must be a string in the form 'major[.minor[.revision]]'`.

```
>> version
ans = 7.14.0.739 (R2012a)
>> verLessThan('matlab', 'R2013a')
ans = 0
>> verLessThan('matlab', '8.1')
ans = 1

```

**Comment by HeikoSchuett** [comment]
Thank you for this find!
It is surprisingly stupid that they changed the way this function works in newer matlab versions...
I changed the file as you suggested
